#mount cifs share as local volumes
#you can create multiple volumes with the same ip
#that's awesome isn't it ?
volumes:
    cifs_volume_name:
      driver: local
      driver_opts:
        type: cifs
        device: '//path/to/share'
        o: 'username=user1,password=user1pwd,gid=...'
volumes:
    static: {}
    cifs_data:
      driver: local
      driver_opts:
        type: cifs
        device: '//192.168.0.150/MEDIA'
        o: 'username=clement,password=clements3cr3tpwd'
    cifs_users:
      driver: local
      driver_opts:
        type: cifs
        device: '//192.168.0.150/USERS'
        o: 'username=clement,password=clements3cr3tpwd'
