version: '3'

services:

  db_test:
    image: mariadb
    container_name: db_test
    environment:
      - "MYSQL_ROOT_PASSWORD=P@ssw0rd"
      - "MYSQL_DATABASE=cells"
      - "MYSQL_USER=pydio"
      - "MYSQL_PASSWORD=P@ssw0rd"
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]

  pydio:
    image: pydio/cells
    container_name: pydio_test
    environment:
      - "CELLS_BIND=192.168.0.150:8083"
      - "CELLS_EXTERNAL=172.18.0.20:8083"
      - "CELLS_NO_SSL=1"
      - "VIRTUAL_HOST=pydio.wilply.fr"
      - "VIRTUAL_PORT=8083"
    volumes:
      - static:/root/.config/pydio/cells/static/pydio
      - cifs_data:/mnt/DATA
    ports:
      - 8083:8083
    links:
      - db_test
      - php
    networks:
      default:
        ipv4_address: 172.18.0.20
  php:
    image: pydio/cells-php-fpm:latest
    container_name: php
    volumes:
      - static:/root/.config/pydio/cells/static/pydio
    expose:
     - 9000

networks:
  default:
    external:
      name: services-net

volumes:
    static: {}
    cifs_data:
      driver: local
      driver_opts:
        type: cifs
        device: '//192.168.0.150/MEDIA'
        o: 'username=clement,password=clements3cr3tpwd'
    cifs_users:
      driver: local
      driver_opts:
        type: cifs
        device: '//192.168.0.150/USERS'
        o: 'username=clement,password=clements3cr3tpwd'
