version: '3'

networks:
  default:
    external:
      name: services-net

services:
  beets:
    image: wilply/beets-automatic
    restart: always
    environment:
      - DISCOGS_TOKEN="mIHoYFstMolzNkvzZoQopOUyCOiHkHXkqHPFaBSl"
      - PGID=2100
      - PUID=2100
      - MODE="move"
      - DEL_INPUT=false
    volumes:
      - /mnt/DATA/DOWNLOAD:/input/
      - /mnt/DATA/MEDIA/Musique:/musiclibrary/music/
      - /mnt/DATA/DOCKER/container_app/docker_beets:/home/abc/.config/beets/
      - /mnt/DATA/MEDIA/beetsmusic.db:/musiclibrary/beetsmusic.db
