version: '3'

networks:
  default:
    external:
      name: dev-net

services:

  cells:
    image: pydio/cells:latest
    container_name: pydio_test
    volumes:
      - static:/root/.config/pydio/cells/static/pydio
    ports:
      - 8090:8080
    environment:
      - CELLS_BIND=localhost:8080
      - CELLS_EXTERNAL=localhost:8080
      - CELLS_NO_SSL=1
    links:
      - db_test:mariadb

  db_test:
    image: mariadb
    container_name: db_test
    environment:
      - "MYSQL_ROOT_PASSWORD: P@ssw0rd
      - "MYSQL_DATABASE: cells
      - "MYSQL_USER: pydio
      - "MYSQL_PASSWORD: P@ssw0rd

  php:
    image: pydio/cells-php-fpm
    container_name: pydio_php
    volumes:
      - static:/root/.config/pydio/cells/static/pydio
    links:
      - db_test:mariadb

volumes:
    static: {}
