version: '3'

#networks:
#  default:
#    external:
#      name: services-net

services:
  pydio:
    image: wilply/pydio_cells:latest
    container_name: pydio_test
    ports:
      - 8888:8888
#    container_name: pydio
#    restart: always
#    volumes:
#      - /mnt/ETC/DOCKER/container_files/09_pydio:/home/abc/.config/
    environment:
      - CELLS_ETERNAL=pydio_test:8888
      - CELLS_BIND=0.0.0.0:8888
      - SSL=0
      - PGID=1500
      - PUID=1500
