version: '3'

networks:
  default:
    external:
      name: services-net

services:
  pydio:
    image: pydio/cells
    #image: wilply/pydio_cells
    container_name: pydio_cells
    ports:
      - 8081:8080
    links:
      - pydio_db
    volumes:
      - /mnt/ETC/DOCKER/container_files/09_pydio/pydio:/root/.config/pydio/cells
    environment:
      - CELLS_NO_SSL=1
      - CELLS_BIND=:8080
      - CELLS_EXTERNAL=:8080
      #- PUID=1500
      #- PGID=1500
     labels:
      - traefik.backend=pydio
      - traefik.frontend.rule=Host:pydio.wilply.fr
      - traefik.port=8080
      - traefik.enable=true
      - traefik.protocol=http

  pydio_db:
    image: mariadb
    container_name: pydio_db
    restart: always
    labels:
      - traefik.enable=false
    volumes:
      - /mnt/ETC/DOCKER/container_files/09_pydio/pydio_db/mysql:/var/lib/mysql
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=cells
      - MYSQL_USERNAME=pydio
      - MYSQL_PASSWORD=pydiopwd
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
