version: "3"

networks:
  default:
    external:
      name: services-net

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8082:80/tcp"
    environment:
      TZ: 'Europe/Paris'
    labels:
      - traefik.backend=pihole
      - traefik.frontend.rule=Host:pihole.wilply.fr
      - traefik.port=8082
      - traefik.enable=true
      - traefik.protocol=http
    volumes:
       - '/mnt/ETC/DOCKER/container_files/10_pihole/etc-pihole/:/etc/pihole/'
       - '/mnt/ETC/DOCKER/container_files/10_pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    dns:
      - 127.0.0.1
      - 9.9.9.9
    cap_add:
      - NET_ADMIN
    restart: unless-stopped