version: "3"

networks:
  services-net:
    external:
      name: services-net
  intranet:
    internal: true

volumes:
  couchdb-data:
  cozy-storage:

services:
  couchdb:
    image: apache/couchdb
    container_name: couchdb_cozy
    restart: always
    volumes:
      - /mnt/ETC/DOCKER/container_files/11_cozy/couchdb:/opt/couchdb/data
    networks:
      - intranet

  redis:
    image: redis:alpine
    container_name: redis_cozy
    restart: always
    networks:
      - intranet

  cozy:
    image: wilply/cozy-stack
    container_name: cozy
    restart: always
    links:
      - couchdb:couchdb
      - redis:redis
    ports:
      - "8080"
      - "6060:6060"
    volumes:
      - /mnt/ETC/DOCKER/container_files/11_cozy/cozy-stack:/cozy/config
    networks:
      - intranet
      - services-net
    labels:
      - traefik.docker.network=services-net
      - traefik.backend=cozy
      - traefik.frontend.rule=HostRegexp:{subdomain:[a-z]+}.cozy.wilply.fr,cozy.wilply.fr
      - traefik.port=8080
      - traefik.enable=true
      - traefik.protocol=http
    depends_on:
      - couchdb
      - redis
