version: '3'

networks:
  default:
    external:
      name: services-net

services:

  reverse-proxy:
    image: traefik:alpine
    command: --api --docker
    ports:
      - 80:80     # Http
      - 8080:8080 # Web UI
      - 443:443   # Https
    labels:
      - traefik.backend=traefik
      - traefik.frontend.rule=Host:traefik.wilply.fr
      - traefik.port=8080
      - traefik.enable=true
      - traefik.protocol=http
      - traefik.frontend.auth.basic=admin:$$apr1$$qHhf.Q.e$$uTBfawp3takoGjAvQiBBS1 #Password
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Listen to docker events (unix sock)
      - /mnt/DATA/DOCKER/container_app/docker_traefik/:/etc/traefik/
