version: '3'

networks:
  default:
    external:
      name: services-net

volumes:
    static: {}
    cifs_media:
      driver: local
      driver_opts:
        type: cifs
        device: '//192.168.0.150/MEDIA'
        o: 'username=media,password=medias3cr3t'

    cifs_clement:
      driver: local
      driver_opts:
        type: cifs
        device: '//192.168.0.150/USERS'
        o: 'username=clement,password=clements3cr3tpwd'

    cifs_domaclena:
      driver: local
      driver_opts:
        type: cifs
        device: '//192.168.0.150/DOMACLENA'
        o: 'username=domaclena,password=domaclenas3cr3t'

    cifs_lecoq:
      driver: local
      driver_opts:
        type: cifs
        device: '//192.168.0.150/LECOQ'
        o: 'username=lecoq,password=lecoqs3cr3t'

services:
  airsonic:
    image: linuxserver/airsonic
    container_name: airsonic
    restart: always
    environment:
      - TZ=Europe/Paris
      - "PGID=2100"
      - "PUID=2100"
      - "JAVA_OPTS=-Xmx768m"
    labels:
      - traefik.backend=airsonic
      - traefik.frontend.rule=Host:airsonic.wilply.fr
      - traefik.port=4040
      - traefik.enable=true
      - traefik.protocol=http
    volumes:
      - /mnt/DATA/DOCKER/container_app/docker_airsonic/data:/config
      - /mnt/DATA/DOCKER/container_app/docker_airsonic/playlists:/playlists
      - /mnt/DATA/DOCKER/container_app/docker_airsonic/podcasts:/podcasts
      - /mnt/DATA/MEDIA/Musique:/music
    ports:
      - 4040:4040

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    restart: always
    environment:
      - PGID=2100
      - PUID=2100
      - TZ=Europe/Paris
    labels:
      - traefik.backend=transmission
      - traefik.frontend.rule=Host:transmission.wilply.fr
      - traefik.port=9091
      - traefik.enable=true
      - traefik.protocol=http
    volumes:
      - /mnt/DATA/DOCKER/container_app/docker_transmission:/config
      - /mnt/DATA/DOWNLOAD:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp

  teamspeak:
    image: mbentley/teamspeak
    container_name: teamspeak
    restart: always
    environment:
      - TZ=Europe/Paris
      - "TS3SERVER_LICENSE=accept"
    volumes:
      - /mnt/DATA/DOCKER/container_app/docker_teamspeak/data:/data
    ports:
      - 9987:9987/udp
      - 10011:10011

  projetweb:
    image: wilply/docker_lemp_server
    container_name: projetweb
    restart: always
    environment:
      - TZ=Europe/Paris
    labels:
      - traefik.backend=projetweb
      - traefik.frontend.rule=Host:projetweb.wilply.fr
      - traefik.port=80
      - traefik.enable=true
      - traefik.protocol=http
    expose:
      - 80
    volumes:
      - /mnt/DATA/DOCKER/container_app/docker_projetweb/IUT_M2105:/app/site

  cells:
    image: pydio/cells:latest
    container_name: cells
    expose:
      - 8080
    environment:
      - CELLS_BIND=0.0.0.0:8080
      - CELLS_EXTERNAL=pydio.wilply.fr
      - CELLS_NO_SSL=1
    labels:
      - traefik.enable=true
      - traefik.backend=cells
      - traefik.frontend.rule=Host:pydio.wilply.fr
      - traefik.port=8888
      - traefik.protocol=http
    volumes:
      - /mnt/DATA/DOCKER/container_app/docker_pydio:/root/.config/pydio/cells/
      - cifs_media:/mnt/media
      - cifs_clement:/mnt/clement
      - cifs_domaclena:/mnt/domaclena
      - cifs_lecoq:/mnt/lecoq
    links:
      - db_cells
      - php-fpm

  db_cells:
    image: mariadb
    container_name: db_cells
    env_file: ./db.env
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    expose:
      - 3306

  php-fpm:
    image: pydio/cells-php-fpm
    container_name: php-fpm
    volumes:
      - /mnt/DATA/DOCKER/container_app/docker_pydio:/root/.config/pydio/cells/
    expose:
      - 9000
