version: "3"

networks:
  services-net:
    external:
      name: services-net
  internal-net:
    internal: true

services:
  couchdb:
    container_name: cozy-couchdb
    image: apache/couchdb
    restart: always
    volumes:
      - /mnt/ETC/DOCKER/container_files/12_cozy/couchdb:/opt/couchdb/data
    networks:
      - internal-net

  redis:
    container_name: cozy-redis
    image: redis:alpine
    restart: always
    volumes:
      - /mnt/ETC/DOCKER/container_files/12_cozy/redis:/data
    networks:
      - internal-net
    command: ["redis-server", "--appendonly", "yes"]

  cozy:
    container_name: cozy-stack
    image: wilply/cozy-stack
    restart: always
    links:
      - couchdb:couchdb
      - redis:redis
    ports:
      - 8080
    volumes:
      - /mnt/ETC/DOCKER/container_files/12_cozy/cozy-stack/config:/cozy/config
      - /mnt/DATA/COZY/storage:/cozy/storage
    networks:
      - internal-net
      - services-net
    environment:
      DOMAIN: 'cozy.wilply.fr'
      UID: 1500
      GID: 1500
      RUN_AS_ROOT: 0
    env_file:
      - cozy.env
    labels:
      - traefik.docker.network=services-net
      - traefik.backend=cozy
      - traefik.frontend.rule=HostRegexp:{subdomain:[a-z]+}.cozy.wilply.fr,cozy.wilply.fr
      - traefik.port=8080
      - traefik.enable=true
      - traefik.protocol=http
    depends_on:
      - couchdb
      - redis
