version: '3'

networks:
  default:
    external:
      name: services-net

services:

  nextcloud:
    image: linuxserver/nextcloud:amd64-latest
    container_name: nextcloud
    restart: always
    expose:
      - 443
    ports:
      - "8090:443"
    environment:
      - TZ=Europe/Paris
      - "PGID=1500"
      - "PUID=1500"
    labels:
      - traefik.enable=true
      - traefik.backend=nextcloud
      - traefik.frontend.rule=Host:nextcloud.wilply.fr
      - traefik.port=443
      - traefik.protocol=https
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.STSPreload=true
    volumes:
      - /mnt/ETC/DOCKER/container_files/05_nextcloud/nextcloud/:/config/www/
      - /mnt/DATA/nextcloud:/data
    links:
      - db_nextcloud

  db_nextcloud:
    image: mariadb
    container_name: db_nextcloud
    restart: always
    env_file: ./db.env
    labels:
      - traefik.enable=false
    volumes:
      - /mnt/ETC/DOCKER/container_files/05_nextcloud/db/:/var/lib/mysql
    expose:
      - 3306
