version: '3'

networks:
  default:
    external:
      name: services-net

services:

  nextcloud:
    image: nextcloud:stable
    container_name: nextcloud
    restart: always
    user: "1500:1500"
    expose:
      - 80
    labels:
      - traefik.enable=true
      - traefik.backend=nextcloud
      - traefik.frontend.rule=Host:nextcloud.wilply.fr
      - traefik.port=80
      - traefik.protocol=http
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.STSPreload=true
    volumes:
      - /mnt/ETC/DOCKER/container_files/05_nextcloud/default_files:/var/www/html/core/skeleton
      - /mnt/ETC/DOCKER/container_files/05_nextcloud/nextcloud/:/var/www/html/
    links:
      - db_nextcloud

  db_nextcloud:
    image: mariadb
    container_name: db_nextcloud
    restart: always
    env_file: ./db.env
    labels:
      - traefik.enable=false
    volumes:
      - /mnt/ETC/DOCKER/container_files/05_db_nextcloud:/var/lib/mysql
    expose:
      - 3306
