version: '3'

networks:
  default:
    external:
      name: services-net

services:
  airsonic:
    image: linuxserver/airsonic
    container_name: airsonic
    restart: always
    environment:
      - TZ=Europe/Paris
      - "PGID=2100"
      - "PUID=2100"
      - "JAVA_OPTS=-Xmx768m"
    labels:
      - traefik.backend=airsonic
      - traefik.frontend.rule=Host:airsonic.wilply.fr
      - traefik.port=4040
      - traefik.enable=true
      - traefik.protocol=http
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.STSPreload=true
    volumes:
      - /mnt/DATA/DOCKER/container_app/docker_airsonic/data:/config
      - /mnt/DATA/DOCKER/container_app/docker_airsonic/playlists:/playlists
      - /mnt/DATA/DOCKER/container_app/docker_airsonic/podcasts:/podcasts
      - /mnt/DATA/MEDIA/Musique:/music
    ports:
      - 4040:4040

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    restart: always
    environment:
      - PGID=2100
      - PUID=2100
      - TZ=Europe/Paris
    labels:
      - traefik.backend=transmission
      - traefik.frontend.rule=Host:transmission.wilply.fr
      - traefik.port=9091
      - traefik.enable=true
      - traefik.protocol=http
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.STSPreload=true
    volumes:
      - /mnt/DATA/DOCKER/container_app/docker_transmission:/config
      - /mnt/DATA/DOWNLOAD:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp

  teamspeak:
    image: mbentley/teamspeak
    container_name: teamspeak
    restart: always
    labels:
      - traefik.enable=false
    environment:
      - TZ=Europe/Paris
      - "TS3SERVER_LICENSE=accept"
    volumes:
      - /mnt/DATA/DOCKER/container_app/docker_teamspeak/data:/data
    ports:
      - 9987:9987/udp
      - 10011:10011

  projetweb:
    image: wilply/docker_lemp_server
    container_name: projetweb
    restart: always
    environment:
      - TZ=Europe/Paris
    labels:
      - traefik.backend=projetweb
      - traefik.frontend.rule=Host:projetweb.wilply.fr
      - traefik.port=80
      - traefik.enable=true
      - traefik.protocol=http
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.STSPreload=true
    expose:
      - 80
    volumes:
      - /mnt/DATA/DOCKER/container_app/docker_projetweb/IUT_M2105:/app/site
