version: '3'

networks:
  default:
    external:
      name: services-net

services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    restart: always
    environment:
      - PGID=2100
      - PUID=2100
      - TZ=Europe/Paris
    labels:
      - traefik.backend=transmission
      - traefik.frontend.rule=Host:transmission.wilply.fr
      - traefik.port=9091
      - traefik.enable=true
      - traefik.protocol=http
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.STSPreload=true
    volumes:
      - /mnt/DATA/DOCKER/container_app/docker_transmission:/config
      - /mnt/DATA/DOWNLOAD:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp

  headphones:
    image: linuxserver/headphones
    container_name: headphones
    restart: always
    environment:
      - PGID=2100
      - PUID=2100
    labels:
      - traefik.backend=headphones
      - traefik.frontend.rule=Host:headphones.wilply.fr
      - traefik.port=8181
      - traefik.enable=true
      - traefik.protocol=http
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.STSPreload=true
    volumes:
      - /mnt/DATA/MEDIA/Musique:/music
      - /mnt/DATA/DOCKER/container_app/docker_headphones:/config
      - /mnt/DATA/DOWNLOAD:/downloads
    expose:
      - 8181
    links:
      - jackett
      - transmission

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: always
    environment:
      - PGID=2100
      - PUID=2100
    labels:
      - traefik.backend=jackett
      - traefik.frontend.rule=Host:jackett.wilply.fr
      - traefik.port=9117
      - traefik.enable=true
      - traefik.protocol=http
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.STSPreload=true
      - traefik.frontend.auth.basic=admin:$$apr1$$D7D5KXZh$$T9JwcejybGDE0YhjqiwHs0
    volumes:
      - /mnt/DATA/DOCKER/container_app/docker_jackett:/config
    expose:
      - 9117
