version: '3'

networks:
  default:
    external:
      name: services-net

services:

  beets:
    image: wilply/beets-automatic
    container_name: beets
    restart: always
    environment:
      - "DISCOGS_TOKEN=mIHoYFstMolzNkvzZoQopOUyCOiHkHXkqHPFaBSl"
      - PGID=1500
      - PUID=1500
      - "MODE=move"
      - "DEL_INPUT=false"
    labels:
      - traefik.enable=false
    volumes:
      - /mnt/DATA/DOWNLOAD:/input/
      - /mnt/DATA/MEDIA/Musique:/musiclibrary/music/
      - /mnt/ETC/DOCKER/container_files/02_beets:/home/abc/.config/beets/
      - /mnt/DATA/MEDIA/beetsmusic.db:/musiclibrary/beetsmusic.db

  headphones:
    image: linuxserver/headphones
    container_name: headphones
    restart: always
    environment:
      - PGID=1500
    labels:
      - traefik.backend=headphones
      - traefik.frontend.rule=Host:headphones.wilply.fr
      - traefik.port=8181
      - traefik.enable=true
      - traefik.protocol=http
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.headers.STSPreload=true
    volumes:
      - /mnt/DATA/MEDIA/Musique:/music
      - /mnt/ETC/DOCKER/container_files/02_headphones:/config
      - /mnt/DATA/DOWNLOAD:/downloads
    ports:
      - 8181:8181
    links:
      - jackett
      - transmission
